txgh:
    github:
        repos:
            # This name should be org/repo
            LarissaLane/sinatra-i18n-example:
                api_username: "<%= ENV['github_repo_config_api_username'] %>"
                api_token: "<%= ENV['github_repo_config_api_token'] %>"
                push_source_to: "sinatra-1"
                branch: "master"
                webhook_secret: "<%= ENV['github_repo_config_webhook_secret'] %>"
    transifex:
        projects:
            # This name should match the transifex project name, without org name
            sinatra-1:
                tx_config: "<%= ENV['transifex_project_config_tx_config'] %>"
                api_username: "<%= ENV['transifex_project_config_api_username'] %>"
                api_password: "<%= ENV['transifex_project_config_api_password'] %>"
                push_translations_to: "LarissaLane/sinatra-i18n-example"
                push_trigger: "reviewed"
                webhook_secret: "<%= ENV['transifex_project_config_webhook_secret'] %>"
