txgh:
    github:
        repos:
            # This name should be org/repo
            LarissaLane/sinatra-i18n-example:
                api_username: "<%= ENV['GITHUB_USERNAME'] %>"
                api_token: "<%= ENV['GITHUB_TOKEN'] %>"
                push_source_to: "sinatra-1"
                branch: "heads/master"
                webhook_secret: "<%= ENV['GITHUB_WEBHOOK_SECRET'] %>"
    transifex:
        projects:
            # This name should match the transifex project name, without org name
            sinatra-1:
                tx_config: "<%= ENV['TX_CONFIG_PATH'] %>"
                api_username: "<%= ENV['TX_USERNAME'] %>"
                api_password: "<%= ENV['TX_PASSWORD'] %>"
                push_translations_to: "LarissaLane/sinatra-i18n-example"
                push_trigger: "reviewed"
